### ISSUE TITLE
Last git pull DMR IPSC error.... 

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#114]
Logging to the master has failed......

**Comment by iw9grl** [comment]
compiling with HD44780 makefile

**Comment by g0wfv** [comment]
No problems here ... do a make clean and recompile to be sure you are
getting a 'clean' executable - Nothing's changed on the network side since;
the only changes I made are to the HD44780 code itself.

tonyc@mmdvm_home:/opt/MMDVMHost $ sudo git pull
Updating 18a833c..ef0ebb4
Fast-forward
 DMRIds.dat          | 475
++++++++++++++++++++++++++++++++++++++++++++++++++--
 HD44780.cpp         |  44 ++++-
 HD44780.h           |  56 ++++++-
 HD44780.md          |   2 +-
 MMDVM.ini           |   2 -
 Makefile.Pi.PCF8574 |  24 +++
 README.md           |   4 +-
 7 files changed, 580 insertions(+), 27 deletions(-)
 create mode 100644 Makefile.Pi.PCF8574
tonyc@mmdvm_home:/opt/MMDVMHost $ sudo make clean
rm -f MMDVMHost *.o *.d *.bak *~
tonyc@mmdvm_home:/opt/MMDVMHost $ sudo make
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
AMBEFEC.o AMBEFEC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Display.o Display.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRControl.o DMRControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRCSBK.o DMRCSBK.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRData.o DMRData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRDataHeader.o DMRDataHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMREMB.o DMREMB.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMREmbeddedLC.o DMREmbeddedLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRFullLC.o DMRFullLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRIPSC.o DMRIPSC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRLookup.o DMRLookup.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRLC.o DMRLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRShortLC.o DMRShortLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRSlot.o DMRSlot.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DMRSlotType.o DMRSlotType.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DStarControl.o DStarControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DStarHeader.o DStarHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DStarNetwork.o DStarNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
DStarSlowData.o DStarSlowData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Golay2087.o Golay2087.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Golay24128.o Golay24128.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Hamming.o Hamming.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
HD44780.o HD44780.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Log.o Log.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
MMDVMHost.o MMDVMHost.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Modem.o Modem.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Nextion.o Nextion.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
NullDisplay.o NullDisplay.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
QR1676.o QR1676.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
RS129.o RS129.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
SerialController.o SerialController.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
SHA256.o SHA256.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
StopWatch.o StopWatch.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Sync.o Sync.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
TFTSerial.o TFTSerial.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Thread.o Thread.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Timer.o Timer.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
UDPSocket.o UDPSocket.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
Utils.o Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
YSFControl.o YSFControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
YSFConvolution.o YSFConvolution.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
YSFFICH.o YSFFICH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
YSFNetwork.o YSFNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o
YSFPayload.o YSFPayload.cpp
g++ AMBEFEC.o BPTC19696.o Conf.o CRC.o Display.o DMRControl.o DMRCSBK.o
DMRData.o DMRDataHeader.o DMREMB.o DMREmbeddedLC.o DMRFullLC.o DMRIPSC.o
DMRLookup.o DMRLC.o DMRShortLC.o DMRSlot.o DMRSlotType.o DStarControl.o
DStarHeader.o DStarNetwork.o DStarSlowData.o Golay2087.o Golay24128.o
Hamming.o HD44780.o Log.o MMDVMHost.o Modem.o Nextion.o NullDisplay.o
QR1676.o RS129.o SerialController.o SHA256.o StopWatch.o Sync.o TFTSerial.o
Thread.o Timer.o UDPSocket.o Utils.o YSFControl.o YSFConvolution.o
YSFFICH.o YSFNetwork.o YSFPayload.o -g -O3 -Wall -std=c++0x -pthread
-DHD44780 -I/usr/local/include -lwiringPi -lwiringPiDev -lpthread -o
MMDVMHost
tonyc@mmdvm_home:/opt/MMDVMHost $ sudo ./MMDVMHost ./MMDVM.ini
I: 2016-07-01 21:35:27.320 This software is for use on amateur radio
networks only,
I: 2016-07-01 21:35:27.322 it is to be used for educational purposes only.
Its use on
I: 2016-07-01 21:35:27.322 commercial networks is strictly prohibited.
I: 2016-07-01 21:35:27.324 Copyright(C) 2015, 2016 by Jonathan Naylor,
G4KLX and others
M: 2016-07-01 21:35:27.325 MMDVMHost-20160624 is starting
I: 2016-07-01 21:35:27.326 General Parameters
I: 2016-07-01 21:35:27.326     Callsign: G0WFV
I: 2016-07-01 21:35:27.326     Duplex: no
I: 2016-07-01 21:35:27.327     Timeout: 180s
I: 2016-07-01 21:35:27.327     RF Mode Hang: 10s
I: 2016-07-01 21:35:27.327     Net Mode Hang: 10s
I: 2016-07-01 21:35:27.327     D-Star: enabled
I: 2016-07-01 21:35:27.327     DMR: enabled
I: 2016-07-01 21:35:27.327     YSF: disabled
I: 2016-07-01 21:35:27.328 Modem Parameters
I: 2016-07-01 21:35:27.328     Port: /dev/ttyAMA0
I: 2016-07-01 21:35:27.328     RX Invert: no
I: 2016-07-01 21:35:27.328     TX Invert: yes
I: 2016-07-01 21:35:27.329     PTT Invert: no
I: 2016-07-01 21:35:27.329     TX Delay: 100ms
I: 2016-07-01 21:35:27.329     DMR Delay: 0 (0.0ms)
I: 2016-07-01 21:35:27.329     RX Level: 50%
I: 2016-07-01 21:35:27.329     TX Level: 50%
I: 2016-07-01 21:35:27.329     RX Frequency: 434600000Hz
I: 2016-07-01 21:35:27.329     TX Frequency: 434600000Hz
I: 2016-07-01 21:35:27.330     Osc. Offset: 0ppm
M: 2016-07-01 21:35:27.330 Opening the MMDVM
I: 2016-07-01 21:35:29.342 MMDVM protocol version: 1, description: DVMEGA
HR2.29
I: 2016-07-01 21:35:29.362 Display Parameters
I: 2016-07-01 21:35:29.362     Type: HD44780
I: 2016-07-01 21:35:29.362     Rows: 2
I: 2016-07-01 21:35:29.362     Columns: 16
I: 2016-07-01 21:35:29.362     Pins: 3,0,6,1,2,4
I: 2016-07-01 21:35:29.362     PWM Backlight: yes
I: 2016-07-01 21:35:29.362     PWM Pin: 21
I: 2016-07-01 21:35:29.362     PWM Bright: 100
I: 2016-07-01 21:35:29.362     PWM Dim: 16
I: 2016-07-01 21:35:29.362     Clock Display: yes
I: 2016-07-01 21:35:29.362     Display UTC: no
I: 2016-07-01 21:35:29.626 D-Star Network Parameters
I: 2016-07-01 21:35:29.627     Gateway Address: 127.0.0.1
I: 2016-07-01 21:35:29.628     Gateway Port: 20010
I: 2016-07-01 21:35:29.629     Local Port: 20011
M: 2016-07-01 21:35:29.630 Opening D-Star network connection
I: 2016-07-01 21:35:29.631 DMR Network Parameters
I: 2016-07-01 21:35:29.633     Address: bm-dmr.uk
I: 2016-07-01 21:35:29.633     Port: 62031
I: 2016-07-01 21:35:29.633     Local: random
I: 2016-07-01 21:35:29.633     Slot 1: disabled
I: 2016-07-01 21:35:29.633     Slot 2: enabled
I: 2016-07-01 21:35:29.759 Info Parameters
I: 2016-07-01 21:35:29.760     Callsign: G0WFV
I: 2016-07-01 21:35:29.761     RX Frequency: 434600000Hz
I: 2016-07-01 21:35:29.762     TX Frequency: 434600000Hz
I: 2016-07-01 21:35:29.764     Power: 1W
I: 2016-07-01 21:35:29.764     Latitude: 0.000000deg N
I: 2016-07-01 21:35:29.764     Longitude: 0.000000deg E
I: 2016-07-01 21:35:29.764     Height: 0m
I: 2016-07-01 21:35:29.764     Location: "Lincoln, UK"
I: 2016-07-01 21:35:29.765     Description: "Multi-Mode Hotspot"
I: 2016-07-01 21:35:29.765     URL: "g0wfv.wordpress.com"
M: 2016-07-01 21:35:29.765 Opening DMR IPSC
I: 2016-07-01 21:35:29.765 D-Star Parameters
I: 2016-07-01 21:35:29.765     Module: B
I: 2016-07-01 21:35:29.766     Self Only: yes
I: 2016-07-01 21:35:29.766 DMR Parameters
I: 2016-07-01 21:35:29.767     Id: 2351705
I: 2016-07-01 21:35:29.767     Color Code: 1
I: 2016-07-01 21:35:29.767     Self Only: no
I: 2016-07-01 21:35:29.767     Prefixes: 0
I: 2016-07-01 21:35:29.768     Lookup File: DMRIds.dat
I: 2016-07-01 21:35:29.768     Call Hang: 3s
I: 2016-07-01 21:35:29.768     TX Hang: 4s
I: 2016-07-01 21:35:30.029 Loaded 38467 DMR Ids to the callsign lookup table
M: 2016-07-01 21:35:30.058 MMDVMHost-20160624 is running
M: 2016-07-01 21:35:39.860 Logged into the master successfully


On Fri, Jul 1, 2016 at 8:58 PM iw9grl <notifications@github.com> wrote:

> compiling with HD44780 makefile
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/114#issuecomment-230035054>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4s3GzKJjAiEcCs37Ut3baWFsKFM5ks5qRXFNgaJpZM4JDcGG>
> .
>
-- 

A J Corbett

G0WFV

**Comment by iw9grl** [comment]
Hi Tony
trying make clean and "make -f Makefile.PI.HD44780 " again, updated the ini with new Modehang, no other change in the ini, I have always DMR IPS Closed Failed to connect to the server......  using the previous MMDVMHost no connection issue found it works well.....

**Comment by phl0** [comment]
Hi guys,

I heard from others that they have problems logging into the (German) master even with older versions. Did you actually try a version from a commit before? If yes, which commit id?

   vy73 de Florian DF2ET

**Comment by phl0** [comment]
Guys,

i just had a look at my own MMDVMHost. It does also does not log into the master anymore. Revision is ef0ebb4. The problem is probably is on the BM side.

   vy73 de Florian DF2ET

**Comment by iw9grl** [comment]
Hi Florian

I'm using Version: 20160614 and it works well , no problme to connect to the server !
Yesterday evening after the git pull, DMR IPSC problems, connection to server failed !!!!
I don't know why .....
I can try to compile using the Makefile standard and not the Makefile.PI.HD44780 .........

I will ask to you asap ...
73 de Daniele IW9GRL

**Comment by g0wfv** [comment]
When you do a make clean, compile all the source code, not just the hd44780
code.

make clean ; make

Sounds like there are potential issues at the BM end; mine is sitting here
rock solid on UK master.

On Sat, 2 Jul 2016 10:41 iw9grl, <notifications@github.com> wrote:

> Hi Florian
>
> I'm using Version: 20160614 and it works well , no problme to connect to
> the server !
> Yesterday evening after the git pull, DMR IPSC problems, connection to
> server failed !!!!
> I don't know why .....
> I can try to compile using the Makefile standard and not the
> Makefile.PI.HD44780 .........
>
> I will ask to you asap ...
> 73 de Daniele IW9GRL
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/114#issuecomment-230093284>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4okjWFXUz899EtjTNjC5fUhSP8xoks5qRjJWgaJpZM4JDcGG>
> .
>
-- 

A J Corbett

G0WFV

**Comment by iw9grl** [comment]
Sorry Tony
but if I don't compile the HD44780 Makefile I cannot use the display !!!! do you confirm ?
73

**Comment by g0wfv** [comment]
Yes.

You need do the following once ...

cp Makefile.Pi.HD44780 Makefile

... then ...

make clean ; make

On Sat, 2 Jul 2016 12:42 iw9grl, <notifications@github.com> wrote:

> Sorry Tony
> but if I don't compile the HD44780 Makefile I cannot use the display !!!!
> do you confirm ?
> 73
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/114#issuecomment-230097790>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4o64GHR0CX1B6ONaYM7bsB8MuewSks5qRk6ngaJpZM4JDcGG>
> .
>
-- 

A J Corbett

G0WFV

**Comment by iw9grl** [comment]
Typing  make -f Makefile.Pi.HD44780 is the same thing !!!!

**Comment by g0wfv** [comment]
So it is! I didn't look at the whole command line! Your problem must be at
the master end in that case.

On Sat, 2 Jul 2016 12:55 iw9grl, <notifications@github.com> wrote:

> Typing make -f Makefile.Pi.HD44780 is the same thing !!!!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/114#issuecomment-230098265>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4oc_7itC-4KSacJx0W49rX9WFPPnks5qRlGagaJpZM4JDcGG>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Have you tried reverting to make sure the problem isn't coincidental with your git pull?

**Comment by iw9grl** [comment]
sure the previous works well!!!!!!

**Comment by g0wfv** [comment]
Looks like I've found the issue and have submitted a fix.

If you do a git pull and recompile now, it should work again.

Please let me know if anything is still broken.

Tony

On Sat, 2 Jul 2016 14:38 iw9grl, <notifications@github.com> wrote:

> sure the previous works well!!!!!!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/114#issuecomment-230102139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4o6uAGWZ2Q4RHKFGWuwiZ0JUMTXoks5qRmnpgaJpZM4JDcGG>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Now tested working by DF2ET.

**Comment by iw9grl** [comment]
I will verify afternoon .... thank you 73

**Comment by iw9grl** [comment]
I confirm that the last update works well, no issue con BM connection.
