### ISSUE TITLE
TG acknowledge

### ISSUE THREAD

**Issue by ke5di** [g4klx/MMDVMHost#148]
Not an issue, but a request:  When changing REFlectors in D-Star, the radio transmits a connected to message.  You get an RF feedback stating the new connection.

FOR DMR:
Is it possible to transmit a similar message when a DMR message is received via RF that changes the existing Trunk Group? 

When using tail -f, you can see the log entry shown the new trunk group... would be nice if a standard message could be 'transmitted' back through the dvmega...

Thanks for reading.
Rick

**Comment by g0wfv** [comment]
Yes and No, because of the way that talkgroups (Trunk Groups as you call them) work.  You aren't "connected" as such to a talkgroup; talkgroups are all live at any one time.  The confusion may be arising from the use of user activated (UA) talkgroups whereby you can request a talkgroup that is normally suppressed be allowed to pass to your repeater/hotspot (you're still not connecting to that talkgroup - you've just requested it be allowed to pass!).  Theoretically you can have quite a few talkgroups configured on either slot at any time and whichever one gets there first is the one you hear on the radio (or not if you're not listening to that TG - that's where Simon's talkgroup re-write code may come in handy!)

For a voice notification  (I assume you mean that when you term it a message?) to be issued, this would have to be sent from the master where the other voice notifications originate (MMDVMHost doesn't have the capability - just the master!)

Or that's my understanding at any rate ....

**Comment by ke5di** [comment]
Thanks for the info.  Mostly, I was trying to avoid keying up the DMR radio Multiple times to 'set' the active TG.  Was thinking an acknowledgement might help.  


Rick
Ke5di
