### ISSUE TITLE
"JitterBuffer" problems

### ISSUE THREAD

**Issue by F1PFC** [g4klx/MMDVMHost#384]
Hi all.

Two days ago I updating MMDVMHost, and I have some problems with "JitterBuffer".

After I stopped totransmit, during between **3 and 7 seconds** (it depends of my TX duration), I can read, on my console, some lines like these :

D: 2018-02-04 16:27:54.704 DMR Slot 2, JitterBuffer: no data available, elapsed=52742ms, raw=881, head=113
D: 2018-02-04 16:27:54.704 DMR Slot 2, JitterBuffer: returning the last received frame
D: 2018-02-04 16:27:54.826 DMR Slot 2, JitterBuffer: no data available, elapsed=52864ms, raw=883, head=115
D: 2018-02-04 16:27:54.826 DMR Slot 2, JitterBuffer: returning the last received frame

And hanging it, I cannot receive my correspondent.

I tried to disable "Jitter" or to change duration (300, 500, 600 or 1000), it is the same.

When I return with my old version (I think November 2017), I have no problem.

Did anybody notice the same phenomena?

Thanks and 73 from F1PFC.

**Comment by narspt** [comment]
I'm also experiencing problems with DMR (connected to BrandMeister) that I thing must be related to these recent JitterBuffer changes. What I notice are lots of random "cuts" while listening to colleagues coming from the net and looking at mmdvmhost logs I see "network watchdog has expired" when that happens (instead of the normal "received network end of voice transmission"), it happens very frequently.

Disabling JitterBuffer with the new option makes things even much worse than if I leave it turned on! (i.e. the cuts and the "network watchdog has expired" lines are much more frequent), with that option disabled it's really impossible to listen anyone... and... my Internet connection is very decent FTTH with excellent latency to our national master:

```
$ sudo ping 193.137.237.12
PING 193.137.237.12 (193.137.237.12) 56(84) bytes of data.
64 bytes from 193.137.237.12: icmp_seq=1 ttl=48 time=3.36 ms
64 bytes from 193.137.237.12: icmp_seq=2 ttl=48 time=2.65 ms
64 bytes from 193.137.237.12: icmp_seq=3 ttl=48 time=2.58 ms
64 bytes from 193.137.237.12: icmp_seq=4 ttl=48 time=2.68 ms
64 bytes from 193.137.237.12: icmp_seq=5 ttl=48 time=3.14 ms
64 bytes from 193.137.237.12: icmp_seq=6 ttl=48 time=2.49 ms
64 bytes from 193.137.237.12: icmp_seq=7 ttl=48 time=2.52 ms
64 bytes from 193.137.237.12: icmp_seq=8 ttl=48 time=2.66 ms
64 bytes from 193.137.237.12: icmp_seq=9 ttl=48 time=2.66 ms
64 bytes from 193.137.237.12: icmp_seq=10 ttl=48 time=2.94 ms
^C
--- 193.137.237.12 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9016ms
rtt min/avg/max/mdev = 2.499/2.773/3.366/0.274 ms
```

With the JitterBuffer option enabled the things are better, the cuts and the "network watchdog has expired" lines show less often, however it still happens...

So I decided today to just downgrade to an old mmdvmhost binary compiled at 03/01 and since using that older version I have no more problems at all (as it used to be), I did leave it whole day in a TG with much activity today and really no more "network watchdog has expired" lines showing in the log at all... and no cuts.

After this experience I really think something is not really ok since these changes and the new JitterBuffer option doesn't help or make it behave as before at all.
