### ISSUE TITLE
DR-1X repeater won't repeat MMDVM setup as Remote Gateway

### ISSUE THREAD

**Issue by WO1VES** [g4klx/MMDVMHost#430]
Greetings All,

I am trying to setup an MMDVM as a remote gateway to a Yaesu DR-1X repeater that doesn't have Internet access at the site.  I am setting it up as for System Fusion on both YSF reflectors and FCS reflectors, and I set the option for "RemoteGateway" in the MMDVM.ini file to "1" but the DR-1X won't repeat anything transmitted from the MMDVM.  Instead, it sees the MMDVM as another repeater and transmits the digital noise in analog mode.

Transmissions from the repeater, to the MMDVM, come through just fine if receiving on another MMDVM or hotspot to a handheld.  But fails on any repeater.

Is there any way of getting the MMDVM to behave like a Wires-X Gateway?  Right now the MMDVM is acting like another repeater, but should act like a gateway.

Thanks!

WO1VES

**Comment by iu7igu** [comment]
Hi WO1VES,
the DR-1X repeater can't repeat MMDVM's transmission because MMDVMHost software send data like repeater and yaesu repeater see this like another repeater and don't work. I hope that this problem will be solved because i need to use a system like your.

**Comment by Skinoku** [comment]
Hi!
I am also trying that to link two rooms and found out that it doesn't work.
It should be running like a regular YSF radio sending just the callsign and the GPS data, **not also the repeater of origin** otherwise the DR-1X will think he is on the same freq with other repeaters and won't repeat avoiding a endless loop.
Any idea how to fix or tell if I can contribute?
Thanks a lot
IU1INZ

**Comment by juribeparada** [comment]
Hi, can you test from my repo:
https://github.com/juribeparada/MMDVMHost

I am trying to figure out this issue, but I don't have any access to a DR-1X.

Andy CA6JAU.

**Comment by Skinoku** [comment]
Dear Andy,
Now I'm away so unable to experiment. 
But I tell a way you can figure out yourself without a DR1. You still need a c4fm radio, of course. 
The ft1d for example on the display shows when talking on a repeater 
*
CALLSING
R>REPEATERCALL
*
Continuously alternating 
For mmdvm it should show on the display just the callsign of the person speaking and nothing else except the gps distance.
To make it even simpler, it should behave like you are taking SIMPLEX with another c4fm radio, otherwise loop protection of the DR1 will engage and won't repeat the mmdvm. 
The SHARK version of hotspot will do exactly what I described and it works well. 

73s IU1INZ Lorenzo

**Comment by juribeparada** [comment]
OK, thanks for you information, but I still need that you or somebody else confirm the change that I did. Then I will continue investigating depending of my free time.
Regards.

**Comment by WO1VES** [comment]
Hi Andy,

I've been running the Pi-Star release, so I will have to figure out how to compile myself.  I'll figure it out, and give your build a try.  Thanks for looking into this.

Brian - WO1VES

**Comment by juribeparada** [comment]
Any news on this?, have anyone tested my changes from my repository?. I will not put any change to the official MMDVMHost until some confirmation.

**Comment by mreckhof** [comment]
Just saw this and may be what's causing a problem for me.  Let me pull this repo and test.

**Comment by juribeparada** [comment]
mreckhof: remember to test this repo: https://github.com/juribeparada/MMDVMHost

**Comment by mreckhof** [comment]
I’ve only been able to do limited testing so far, but it appears to be working for me.  My setup is:

HT Radio —> MMDVM Hotspot —> YSFReflector —> MMDVM RF Bridge (duplex hat) —> DR1-X —> HT Radio

Without the patch I was getting digital noise over audio.  With the patch, I’m getting proper digital communication. 

I’ve also had to set low deviation and using remotegateway=1. 

I’ll do more testing over the next few days as I find the time, but so far, it’s working at least for how I need it to!

Thanks!

**Comment by juribeparada** [comment]
OK, good news that the patch works, I will add to this oficial repo soon.

**Comment by juribeparada** [comment]
Now it is added to the oficial repo

**Comment by mreckhof** [comment]
Thank you, for all you do for the ham community!
