### ISSUE TITLE
feature request;  128x32 oled support

### ISSUE THREAD

**Issue by sonic2wb** [g4klx/MMDVMHost#469]
Would like to use the smaller oled display if possible. useing the premade pi sdcard image. 

Thanks

**Comment by dh47** [comment]
Would be cool if someone could look into this, 28 days and no reply.

**Comment by geekbozu** [comment]
In theory it s already supported via the appropriate LCD mode if the code will actually write to this screen is another story. 
https://github.com/hallard/ArduiPi_OLED/blob/4119148b051a6975816de2319eb6d11f6769499d/ArduiPi_OLED_lib.h#L46

**Comment by ChrisK9EQ** [comment]
The issue is that many of the 0.96" OLEDs on the market use the SSD1106 controller. The standard Adafruit library only supports the SSD1306 controller. The solution is to replace the library with one that supports the SSD1106 or SSD1306 (or buy a different display). See this post for info:https://forum.pistar.uk/viewtopic.php?f=21&t=660
Try to ignore the QRM. :-)

If the library has been updated, this issue can be closed.
