### ISSUE TITLE
Issue on detecting  D-Star session start state after the fast-data changes applied.

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#494]
Recently I noticed some wired logs from MMDVMHost saying that "D-Star session is started" for several times during one session, and it occurs after the fast-data patch is applied. Which may impact on the last seen list logic of dashboard.
Report the issue here first then I will look into that.

PS: I was assuming D-Star session started when a RF header was received OR D-Star header was decoded from the slow data frames. but it was not true after the fast-data mode/state was introduced.

**Comment by shawnchain** [comment]
```
M: 2019-03-03 16:46:13.267 D-Star, received RF header from BG5HHP  /ID31 to        E
M: 2019-03-03 16:46:14.063 D-Star, received RF late entry from BG5HHP  /ID31 to        E
M: 2019-03-03 16:46:16.282 D-Star, switching to fast data mode
M: 2019-03-03 16:46:17.379 D-Star, transmission lost, 3.3 seconds, BER: 0.0%
M: 2019-03-03 16:46:20.660 D-Star, received RF header from BG5HHP  /ID31 to        E
M: 2019-03-03 16:46:22.449 D-Star, switching to fast data mode
M: 2019-03-03 16:46:22.515 D-Star, received RF end of transmission, 1.9 seconds, BER: 0.0%
```

**Comment by shawnchain** [comment]
```
M: 2019-03-03 16:54:07.898 D-Star, received RF header from BG5HHP  /ID31 to        E
M: 2019-03-03 16:54:08.754 D-Star slowData buffer reset  <-- debug statement added by BG5HHP
M: 2019-03-03 16:54:09.116 D-Star, received RF late entry from BG5HHP  /ID31 to        E
M: 2019-03-03 16:54:11.634 D-Star, received RF end of transmission, 2.5 seconds, BER: 2.4%
```

**Comment by g4klx** [comment]
That sounds like a bug. The reception of s valid RF header should mean that the slow data/late entry logic should not be used. I’ve not seen it myself, but please let me know what you find. The slow data decoder is reset on a data sync because slow data headers don’t cross data sync boundaries.


Sent from Yahoo Mail for iPhone


On Sunday, March 3, 2019, 08:13, Shawn <notifications@github.com> wrote:


Recently I noticed some wired logs from MMDVMHost saying that "D-Star session is started" for several times during one session, and it occurs after the fast-data patch is applied. Which may impact on the last seen list logic of dashboard.
Report the issue here first then I will look into that.

PS: I was assuming D-Star session started when a RF header was received OR D-Star header was decoded from the slow data frames. but it was not true after the fast-data mode/state was introduced.

**Comment by shawnchain** [comment]
My bad. This issue is introduced by my mods on MMDVMHost.cpp. My code will disables all mode controllers first before switching the mode which reset the DStarControl internal state. Because the slow data will always be there no matter whether the RF header is received or not, hence the duplicated start is triggered twice.

I will close this issue, and sorry for the false alarm.

While tracing the code I noticed the fast-data mode will be triggered sometimes during a voice session like blow logs, not sure if this is a by-design behavior or not.
```
M: 2019-03-03 22:08:13.860 D-Star, received RF late entry from BG5HHP  /ID31 to        E
M: 2019-03-03 22:08:14.637 D-Star, switching to fast data mode
M: 2019-03-03 22:08:18.065 D-Star, received RF end of transmission, 4.2 seconds, BER: 0.0%
```

**Comment by g4klx** [comment]
That’s good to know. The method used for detecting fast data mode isn’t foolproof as the slow data doesn’t include any FEC. The only repercussions of switching to fast data mode is the loss of FEC reconstruction on the audio for the rest of the trainsmission.


Sent from Yahoo Mail for iPhone


On Sunday, March 3, 2019, 14:13, Shawn <notifications@github.com> wrote:


My bad. This issue is introduced by my mods on MMDVMHost.cpp. My code will disables all mode controllers first before switching the mode which reset the DStarControl internal state. Because the slow data will always be there no matter whether the RF header is received or not, hence the duplicated start is triggered twice.

I will close this issue, and sorry for the false alarm.

While tracing the code I noticed the fast-data mode will be triggered sometimes during a voice session like blow logs, not sure if this is a by-design behavior or not.
M: 2019-03-03 22:08:13.860 D-Star, received RF late entry from BG5HHP  /ID31 to        E
M: 2019-03-03 22:08:14.637 D-Star, switching to fast data mode
M: 2019-03-03 22:08:18.065 D-Star, received RF end of transmission, 4.2 seconds, BER: 0.0%
