### ISSUE TITLE
Compile issue with OLED screen

### ISSUE THREAD

**Issue by F4HWD** [g4klx/MMDVMHost#573]
Hi everyone !

I can't compile MMDVMHost with my OLED screen since the addition of FM mode. Here is a copy of my terminal :

dhs@DHS(rw):/tmp/MMDVMHost$ make -f Makefile.Pi.OLED
echo "const char *gitversion = \"4a923fb27e9789f031052835fdc1c7ef1815204c\";" > GitVersion.h 
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o AMBEFEC.o AMBEFEC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o BCH.o BCH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o CASTInfo.o CASTInfo.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Display.o Display.cpp
Display.cpp: In static member function ‘static CDisplay* CDisplay::createDisplay(const CConf&, CUMP*, CModem*)’:
Display.cpp:645:128: error: invalid new-expression of abstract class type ‘COLE’
 roll, rotate, logosaver, conf.getDMRNetworkSlot1(), conf.getDMRNetworkSlot2());
                                                                              ^

In file included from Display.cpp:39:
OLED.h:40:7: note:   because the following virtual functions are pure within ‘COLED’:
 class COLED : public CDisplay
       ^~~~~
In file included from Display.cpp:19:
Display.h:91:15: note: 	‘virtual void CDisplay::setFMInt()’
  virtual void setFMInt() = 0;
               ^~~~~~~~
make: *** [Makefile.Pi.OLED:27: Display.o] Error 1

Hope you can do something. Thank you. Best 73's de F4HWD Max.

**Comment by g4klx** [comment]
Hi Max
I've added an FM display to the OLED driver. I don't have an OLED display so I don't know if it works or not. Please do another pull from GitHub and try again please.
Jonathan  G4KLX

    On Saturday, 2 May 2020, 20:36:11 BST, F4HWD Max <notifications@github.com> wrote:  
 
 


Hi everyone !

I can't compile MMDVMHost with my OLED screen since the addition of FM mode. Here is a copy of my terminal :

dhs@DHS(rw):/tmp/MMDVMHost$ make -f Makefile.Pi.OLED
echo "const char gitversion = "4a923fb27e9789f031052835fdc1c7ef1815204c";" > GitVersion.h
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o AMBEFEC.o AMBEFEC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o BCH.o BCH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o CASTInfo.o CASTInfo.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Display.o Display.cpp
Display.cpp: In static member function ‘static CDisplay CDisplay::createDisplay(const CConf&, CUMP*, CModem*)’:
Display.cpp:645:128: error: invalid new-expression of abstract class type ‘COLE’
roll, rotate, logosaver, conf.getDMRNetworkSlot1(), conf.getDMRNetworkSlot2());
^

In file included from Display.cpp:39:
OLED.h:40:7: note: because the following virtual functions are pure within ‘COLED’:
class COLED : public CDisplay
^~~~~
In file included from Display.cpp:19:
Display.h:91:15: note: ‘virtual void CDisplay::setFMInt()’
virtual void setFMInt() = 0;
^~~~~~~~
make: *** [Makefile.Pi.OLED:27: Display.o] Error 1

Hope you can do something. Thank you. Best 73's de F4HWD Max.

**Comment by F4HWD** [comment]
Thank you Jonathan, it works perfectly with your patch. Don't hesitate to contact me if you need someone to test the OLED screen. I will now close the issue.

Best 73
