### ISSUE TITLE
direct connection to dmr networks (not via dmrgateway)

### ISSUE THREAD

**Issue by stefansaraev** [g4klx/MMDVMHost#651]
@g4klx is there any chance that you would consider reverting the "simpledmr" changes so people can continue to use mmdvmhost without dmrgateway?

**Comment by shawnchain** [comment]
Direct connection is a ideal for mini OS with weak CPU

**Comment by dk7td** [comment]
Why should I use a gateway if I‘m running dmr only? This is completely useless for me.
Please revert the changes - thanks!

**Comment by g4klx** [comment]
The change was done so that (1) DMR was the same as the other modes that the MMDVM supports, and (2) it makes my job easier. The simpler the host software, the less time I have to spend finding bugs. My change was done purely for technical reasons, not political which some have said. It really is not difficult to run the DMR Gateway with very simple rewrite rules so that the data is passed though. The DMR Gateway does some data augmentation which logically makes more sense to do externally to the host. Ultimately the host is supposed to do two jobs (1) handle the RF protocols for potential repeating, and (2) optionally interface to a non-trivial gateway that handles the networking side. So no, it's not going back. I really don't see the problem with running the gateway.

@dk7td You are vert rude. Are you not capable of running two programs?

**Comment by stefansaraev** [comment]
@g4klx understood, those are, of course, valid reasons. just wanted to say that the networking code is already there and it works really, really good (it is not perfect, but nothing is ever perfect. it is more than good enough). and imho, would be nice to not require one more component (dmrgateway) involved. 

However, I am not here to insist that you should revert it, it is your right to do whatever you think is best with your opensource projectt. And It is sad to hear some have said this happens due to political reasons. I for sure dont think your decision has something to do with any politics.

Thank you for your work on mmdvmhost

**Comment by pa1er** [comment]
I am using mmdvm already a long time for a real repeater. I am not using any of the other modes beside of dmr. This way it is also stable enough and can run very good on a rpi3. Adding additional programs, needing to make rewrite rules etc is not something that would add stability to the system as a whole

Therefore I am indeed in favor for not needing a additional program. Maybe it is possible to have a stable-dmr only version and  a i-can-do-it-all version?

**Comment by g4klx** [comment]
If it works. don't upgrade. If it works, why change anything?
    On Thursday, 5 November 2020, 16:06:31 GMT, Erik-jan roggekamp, PA1ER <notifications@github.com> wrote:  
 
 


I am using mmdvm already a long time for a real repeater. I am not using any of the other modes beside of dmr. This way it is also stable enough and can run very good on a rpi3. Adding additional programs, needing to make rewrite rules etc is not something that would add stability to the system as a whole

Therefore I am indeed in favor for not needing a additional program. Maybe it is possible to have a stable-dmr only version and a i-can-do-it-all version?

**Comment by sq7lrx** [comment]
Just a thumbs up 👍 for @stefansaraev request. It does make sense for me to run MMDVMHost standalone on a very resource constrained platform

**Comment by dk5ras** [comment]
Well, someone can create a DMR fork, repair all that needs still to be repaired, and we have a nicely running DMR-only MMDVMHost. Now we just need to find Mr. Someone :)
